version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_keycloak
      - MARIADB_DATABASE=bitnami_keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:15
    depends_on:
      - mariadb
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_DATABASE_VENDOR=MYSQL
      - KEYCLOAK_DATABASE_HOST=mariadb
      - KEYCLOAK_DATABASE_PORT=3306

volumes:
  mariadb_data:
    driver: local
