version: '2'
services:
  mysql:
    image: docker.io/bitnami/mysql:8.0
    volumes:
      - 'mysql_data:/bitnami/mysql/data'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_keycloak
      - MYSQL_DATABASE=bitnami_keycloak

  keycloak:
    image: docker.io/bitnami/keycloak:15
    depends_on:
      - mysql
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_DATABASE_VENDOR=MYSQL
      - KEYCLOAK_DATABASE_HOST=mysql
      - KEYCLOAK_DATABASE_PORT=3306

volumes:
  mysql_data:
    driver: local
